{{- if .Values.preInstallJob -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "laravel5.fullname" . }}-pre-install-job-{{ .Release.Time.Seconds }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "laravel5.name" . }}-nginx
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: project-env
          secret:
            secretName: project-env
        - name: install-script
          configMap:
            name: {{ template "laravel5.fullname" . }}-{{ .Release.Time.Seconds}}-install
            items:
            - key: install.sh
              path: install.sh
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-phpfpm
          image: "{{ .Values.phpfpmImage.repository }}:{{ .Values.phpfpmImage.tag }}"
          imagePullPolicy: {{ .Values.phpfpmImage.pullPolicy }}
          args: ["{{ .Values.preInstallCommand.first }}",
                "{{ .Values.preInstallCommand.second }}"]
          ports:
            - name: phpfpm
              containerPort: {{ .Values.phpfpmPort }}
              protocol: TCP
          volumeMounts:
            - name: project-env
              mountPath: /var/www/laravel-app/.env
              subPath: .env
            - name: install-script
              mountPath: /var/www/laravel-app/install.sh
              subPath: install.sh
          livenessProbe:
            tcpSocket:
              port: {{ .Values.phpfpmPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: {{ .Values.phpfpmPort }}
            initialDelaySeconds: 300
            timeoutSeconds: 5
          resources:
    {{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
    {{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
    {{ toYaml . | indent 8 }}
    {{- end }}


{{- end -}}
