apiVersion: v1
kind: Secret
metadata:
  name: project-env
  namespace: default
  labels:
    app: {{ template "laravel5.name" . }}
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  .env: |-
{{ .Files.Get "conf/environment" | b64enc | indent 4 }}
