version: '2'
services:
  web:
    image: hassam1989/php-nginx:latest
    container_name: laravel-nginx
    volumes_from:
      - php
    working_dir: /var/www/laravel-app
    ports:
      - 80:80
  php:
    image: hassam1989/php-live:latest
    container_name: laravel-php
    volumes:
      - ./../hassam-docker/:/var/www/laravel-app
      - ./conf/laravel-site.conf:/etc/nginx/conf.d/default.conf
networks:
  default:
    external:
      name: nginx-proxy
