version: '2'
services:
  web:
    image: hassam1989/php-nginx:latest
    container_name: laravel-nginx
    volumes_from:
      - php
    working_dir: /var/www/laravel-app
    ports:
      - 80:80
  php:
    image: hassam1989/php-live:latest
    container_name: laravel-php
    volumes:
      - ./../hassam-docker/:/var/www/laravel-app
      - ./conf/laravel-site.conf:/etc/nginx/conf.d/default.conf
  database:
    image: mysql:5.6
    container_name: database
    volumes:
      - dbdata1:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
volumes:
  dbdata1:
networks:
  default:
    external:
      name: nginx-proxy
