apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ template "laravel5.fullname" . }}-{{ .Release.Time.Seconds }}-phpfpm
  labels:
    app: {{ template "laravel5.name" . }}
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  www.conf: |-
{{ .Files.Get "conf/www.conf" | indent 4 }}
