apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  name: {{ template "laravel5.fullname" . }}-{{ .Release.Time.Seconds }}-cronjob
  defaultMode: 0777
  labels:
    app: {{ template "laravel5.name" . }}
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cron.sh: |-
{{ .Files.Get "conf/cron.sh" | indent 4 }}
  cronjobs: |-
{{ .Files.Get "conf/cronjobs" | indent 4 }}
