apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
  name: {{ template "laravel5.fullname" . }}-{{ .Release.Time.Seconds }}-install
  labels:
    app: {{ template "laravel5.name" . }}
    chart: {{ template "laravel5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  install.sh: |-
{{ .Files.Get "conf/install.sh" | indent 4 }}
